name: Install into repository

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: install jar
      run: mvn install:install-file -DpomFile=pom.xml -Dfile=./target/Ultimate_Economy-API.jar -Dpackaging=jar -DgeneratePom=true -DlocalRepositoryPath=.  -DcreateChecksum=true
        # Deploy to local repo
    - name: Deploy
      run: |
        git add --all
        git stash
        git status
        git branch -a
        git checkout repository
        git stash pop
        git commit -m 'Update API version'
