name: Install into repository

on: 
  push:
    branches: [ dev,master ]
  pull_request:
    branches: [ dev,master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: install jar
      run: | 
        if [ ${{github.ref}} == refs/heads/dev ]
        then
        mvn install:install-file -Dversion=dev -DpomFile=pom.xml -Dfile=./target/Ultimate_Economy-API.jar -Dpackaging=jar -DgeneratePom=true -DlocalRepositoryPath=.  -DcreateChecksum=true;
        elif [ ${{github.ref}} == refs/heads/master ] || [ ${{ github.event.pull_request.base.ref }} == refs/heads/master ]
        then
        mvn install:install-file -DpomFile=pom.xml -Dfile=./target/Ultimate_Economy-API.jar -Dpackaging=jar -DgeneratePom=true -DlocalRepositoryPath=.  -DcreateChecksum=true;
        elif [ ${{ github.event.pull_request.base.ref }} == refs/heads/dev ]
        then
        mvn install:install-file -Dversion=dev -DpomFile=pom.xml -Dfile=./target/Ultimate_Economy-API.jar -Dpackaging=jar -DgeneratePom=true -DlocalRepositoryPath=.  -DcreateChecksum=true;
        fi
    - name: deploy
      run: |
        git config --global user.email "github-actions@users.noreply.github.com"
        git config --global user.name "github-actions"
        git add --all
        git stash
        git checkout repository
        git cherry-pick -n -m1 -Xtheirs stash
        git commit -m 'Update API version'
        git push
        


        

