name: Install into repository

on:
  workflow_dispatch:
    inputs:
      version:
          description: 'API Version'
          required: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: install jar
      run: mvn install:install-file -Dversion=${{ github.event.inputs.version }} -DgroupId=org.ue -DartifactId=Ultimate_Economy-API -Dfile=./target/Ultimate_Economy-API.jar -Dpackaging=jar -DgeneratePom=true -DlocalRepositoryPath=./repository  -DcreateChecksum=true
        # Deploy to local repo
    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: repository
        FOLDER: repository
        GITHUB_TOKEN: ${{secrets.ACTIONS_DEPLOY_KEY}}
