# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  workflow_dispatch:
  push:
    branches: [ master, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v2
      with:
        java-version: '14'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Publish to GitHub Packages Apache Maven
      if: github.ref == 'refs/heads/master'
      run: mvn deploy -s ./settings.xml -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/catch441/Ultimate_Economy-API/
      env:
        USERNAME: ${{ secrets.USERNAME }}
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
